title: Shrikrishna Singh
TITLE: Shrikrishna Singh
description: Life begins at the end of your comfort zone
github.project_tagline: seek discomfort 1
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://sks444.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Shrikrishna Singh"
image: /thumbnail-jumbo.png
twitter:
  username: sks444_
github:
  owner_url: https://github.com/sks444
  owner_name: Shrikrishna Singh
  is_project_page: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

#  site:
facebook:
  username: sks444
  url: fb.com/sks444
#   #profile_id: 1809805629
#   app_id: 1798910940422432 # cayman-blog
#   #authors: lorepirri
# #  admins:
header_pages:
  - blog.md
  - gsoc_archive.md
  - projects.md
  - about.md
  - contact.md

repository: sks444/sks444.github.io
